name: tests

on:
  pull_request:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: deps
        run: npm ci 

      - name: install general cookie parser dependecy
        run: npm install cookie-parser

      - name: tests
        run: npm run test

      - name: eslint
        run: npm run lint

      - name: prettier
        run: npm run format

      - name: build
        run: npm run build 
